export const STARTSESION = "STARTSESION"

export const STARTSESION_ASYNC = "STARTSESION_ASYNC"

export const CLOSESESION = "CLOSESESION"

export const EDITUSER = "EDITUSER"

export const EDITUSER_ASYNC = "EDITUSER_ASYNC"

export const DELETEUSER = "DELETEUSER"

export const DELETEUSER_ASYNC = "DELETEUSER_ASYNC"